on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: mkdir build
    - run: cd build
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile ./harmony/harmony.py
    - uses: actions/upload-artifact@v2
      with:
        name: harmony-binaries
        path: dist
