on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl
    
    - name: Install dependencies
      run: |
        cd harmony
        pip install --upgrade pip
        pip install -r requirements.txt pyinstaller
    
    - name: Build with PyInstaller
      run: |
        cd harmony
        pyinstaller --onefile harmony.py
    
    - name: Upload to Release
      if: github.event_name == 'release'
      run: |
        cd harmony
        gh release upload ${{ github.event.release.tag_name }} ./dist/harmony
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload as Artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: harmony
        path: ./harmony/dist/harmony