
name: Build Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: harmony

    - uses: actions/upload-artifact@v2
      with:
        name: harmony
        path: src/dist/linux
